owner: galaxy-australia
name: glycombo
categories:
- Glycomics
description: GlyCombo is an open source software for combinatorial glycan composition determination to identify glycans in MS acquisitions of glycan-containing samples in text or mzML formats.
long_description: GlyCombo is an open source software for combinatorial glycan composition determination to identify glycans in MS acquisitions of glycan-containing samples in text or mzML formats. This application enables rapid extraction of precursor m/z values from mzML files, a vendor-neutral format that ensures cross-platform compatibility.
remote_repository_url: 
homepage_url: https://proteaglyco.com/glycombo/